/**
 * Parks — state and regional.
 *
 * Same convention as everything else here: `null` means UNVERIFIED, never
 * "no". A park with `camping: null` has not been checked; it does not lack a
 * campground. Rendering those as "No" would invent facts ten at a time.
 */

export interface Reservation {
  /** null = we haven't established whether one is needed. */
  required: boolean | null;
  /**
   * WHEN the requirement bites, which is not the same question as whether
   * one exists.
   *
   * Swallow Falls needs a reservation at weekends and on holidays, and lets
   * you walk in on a Tuesday. The badge said "RESERVATION REQUIRED" flatly
   * and the page opened "You can't just turn up" — true of two days in seven,
   * and read as true of all of them. Someone reads that on a Wednesday
   * morning and drives somewhere else for no reason.
   *
   * `null` means the scope isn't established, and the wording stays general.
   */
  scope?: "always" | "weekends" | null;
  window: string | null;
  days: string | null;
  bookAhead: string | null;
  note: string | null;
  /** Entry windows, where the park sells timed slots rather than open entry. */
  slots?: string[] | null;
}

/**
 * A published correction.
 *
 * /how-we-verify/ promises that when we get something wrong we fix it, re-date
 * it, and say on the page that we did. A promise like that is worth nothing
 * without somewhere for it to live, so corrections are part of the record and
 * render on the page rather than being edited away in a commit nobody reads.
 */
export interface Correction {
  /** ISO date the fix was made. */
  date: string;
  /** What we had said. Stated plainly, not softened. */
  was: string;
  /** What it actually is, and how we established that. */
  now: string;
}

/**
 * A field report — someone who was actually there.
 *
 * /how-we-verify/ says a report becomes a dated fact if we can use it. That
 * promise needs somewhere to live, or reports quietly turn into unattributed
 * prose and the site loses the thing it sells.
 *
 * A first-hand visit legitimately counts as `confirmed` under the method
 * ("we called, visited, or asked"). But it confirms a FIELD, not a record:
 * standing in the parking lot tells you where the restrooms are, and nothing
 * about the fee schedule. So reports attach here, name what they bear on, and
 * the record's own tier is unaffected until the rest is checked.
 *
 * `visitedOn` is separate from `receivedOn` on purpose. A report from someone
 * who was there last August is worth less than one from Tuesday, and a site
 * that stamps dates on everything cannot be vague about which date it means.
 */
export interface FieldReport {
  /** ISO date we received it. */
  receivedOn: string;
  /** ISO date they were there. null when they didn't say — and it shows. */
  visitedOn: string | null;
  /** Who. A name, "a reader", or the maintainer. */
  from: string;
  what: string;
  /** Which fields this bears on, for display beside them. */
  affects?: string[];
}

/** A photograph attached to a record. Shape mirrors Photo.astro's props. */
export interface Photo {
  file: string;
  alt: string;
  caption?: string | null;
  credit: string;
  /**
   * When it was taken: `YYYY-MM-DD`, `YYYY-MM`, or null when it isn't known.
   * Renders as "4 Aug 2026", "July 2026" or "date not given" respectively.
   */
  takenOn: string | null;
  portrait?: boolean;
  /**
   * Where to anchor the crop on a listing thumbnail, as a CSS object-position.
   * Defaults to centre.
   *
   * Thumbnails are a fixed 16:9 box and most of these photos are 4:3, so a
   * centre crop throws away the top and bottom eighth. That is usually sky and
   * gravel, and occasionally it is the animal — the first card built here
   * cropped a tortoise's shell off and left a fence. Only set this when the
   * default actually loses the subject.
   */
  focus?: string;
}

/**
 * A field note.
 *
 * Not a fact and not a correction. It is the stuff a database can't hold: the
 * fountain that doesn't work, the walk from the car being longer than the map
 * suggests, the bugs at six in the evening. Dated, signed, first person.
 *
 * WHY IT IS DELIBERATELY NOT A VERIFIED FACT
 *
 * A verified fact is checked with whoever sets the rule and holds until they
 * change it. A field note is one person on one day, and next week the fountain
 * might be fixed. Rendering them the same way would let an impression harden
 * into a claim, which is the failure this whole site is built against. So they
 * get their own block, their own styling, and a byline — and the facts table
 * stays untouched by them.
 *
 * They are also the only thing here that cannot be generated by someone who
 * never went.
 */
export interface FieldNote {
  /** ISO date I was there. Not the date I typed it up. */
  date: string;
  /** Who. Free text so a reader's note can be credited by name. */
  author: string;
  body: string;
  /** Optional photo, keyed like Photo.file. */
  photo?: string | null;
}

/**
 * The verdict.
 *
 * One or two sentences a database could not produce. A fact, then what I
 * actually think about that fact.
 *
 * This is the thing the site was missing. It has the most rigorous data of any
 * guide to this county and, until now, said nothing about anything. The
 * facilities table tells you a park has restrooms. The verdict tells you the
 * walk from the car is longer than it looks and the bugs are bad at six.
 *
 * Rules: no adjective stacks, no closing epigram, and it has to contain
 * something only somebody who went could know. If it reads like it could have
 * been written from the DNR page, delete it and write it again.
 */
export interface Verdict {
  /** One or two sentences. Fact, then reaction. */
  text: string;
  /** ISO date. A verdict ages like everything else here. */
  on: string;
}

export interface StateParkFeatures {
  waterfall: boolean | null;
  /** Sand you can sit on. Distinct from `swimming`, which is about the water. */
  beach: boolean | null;
  swimming: boolean | null;
  /**
   * Added after a reader pointed out Deep Creek Lake has them and the schema
   * had nowhere to say so. State parks had no restroom field at all, which
   * meant the one question people ask most could only be answered for town
   * parks.
   */
  restrooms: boolean | null;
  /**
   * Somewhere to sit and eat. Added when a report named picnic areas at a
   * state park and there was nowhere to record it — town parks had the field
   * and state parks didn't. Third schema gap a field report has found, after
   * restrooms and boat rentals, and all three the same shape: the dataset was
   * built from what agencies publish rather than from what people ask.
   */
  picnic: boolean | null;
  /**
   * Hot showers. Fourth schema gap a field report has found, and the same
   * shape as the other three.
   *
   * This one matters more than it looks. A shower is usually a campground
   * building, and campground buildings are usually for campers only — so
   * "showers: true" and "you can rinse the lake off before the drive home"
   * are not the same claim. The boolean only says they exist; who may use
   * them goes in `warnings`, the same place Herrington Manor's dogs-but-not-
   * on-the-sand rule lives. State parks have no `access` field — town parks
   * grew one for the 4-H centre and this dataset never did.
   */
  showers: boolean | null;
  camping: boolean | null;
  cabins: boolean | null;
  trails: boolean | null;
  boatLaunch: boolean | null;
  /** Renting a boat AT the park — not a private marina elsewhere on the lake. */
  boatRentals: boolean | null;
  fishing: boolean | null;
  winterUse: boolean | null;
  petsAllowed: boolean | null;
}

export interface StatePark {
  slug: string;
  name: string;
  kind: string;
  town: string;
  acres: number | null;
  blurb: string;
  features: StateParkFeatures;
  reservation: Reservation;
  fee: {
    note: string;
    amount: number | null;
    /** Maryland charges per PERSON in summer and per VEHICLE off-season. */
    schedule?: { when: string; resident: string; nonResident: string }[] | null;
    passes?: string | null;
  };
  /** Where you find a person, a shop, or a pass. Mostly unchecked so far. */
  services?: {
    parkOffice: string | null;
    officePhone: string | null;
    officeAddress: string | null;
    giftShop: boolean | null;
    campStore: boolean | null;
    passesSoldHere: boolean | null;
    note: string | null;
  };
  warnings: string[];
  phone: string | null;
  hours: string | null;
  sources: { label: string; url: string; note?: string | null }[];
  sourcedOn: string | null;
  verifiedDate: string | null;
  verifiedSource: string | null;
  outstanding?: string[];
  corrections?: Correction[];
  reports?: FieldReport[];
  photos?: Photo[];
  fieldNotes?: FieldNote[];
  verdict?: Verdict;
}

export interface Restrooms {
  present: boolean | null;
  type: "permanent" | "portable" | null;
  seasonal: boolean | null;
  /**
   * The catch, in three or four words — "sometimes locked", "campers only".
   *
   * Added because a reader scanning a card sees the summary answer and nothing
   * else, and "Yes" for a block that is often locked is the kind of true
   * statement that strands somebody. The caveat rides along with the answer
   * everywhere it appears, rather than sitting in a note further down the page
   * that a scanner never reaches.
   */
  caveat?: string | null;
  note: string | null;
  /** Field-level provenance — a toilet gets confirmed long before a park does. */
  confirmedOn?: string | null;
  confirmedBy?: string | null;
}

export interface RegionalFacilities {
  playground: boolean | null;
  swimming: boolean | null;
  beach: boolean | null;
  picnic: boolean | null;
  pavilion: boolean | null;
  grills: boolean | null;
  trails: boolean | null;
  sports: boolean | null;
  boatLaunch: boolean | null;
  fishing: boolean | null;
  pavedPath: boolean | null;
  winterUse: boolean | null;
}

export interface RegionalPark {
  slug: string;
  name: string;
  operator: string;
  town: string;
  address: string;
  acres: number | null;
  blurb: string;
  restrooms: Restrooms;
  facilities: RegionalFacilities;
  accessibility: string | null;
  /**
   * WHO MAY ACTUALLY USE IT.
   *
   * Added for the 4-H center, where the honest answer is neither "public
   * park" nor "closed": part is open, part is program-and-hire only, and a
   * facilities table alone would send a family there to swim in water they
   * cannot get to. Where this is null the record is an ordinary public park.
   */
  access: string | null;
  hours: string | null;
  hoursNote: string | null;
  phone: string | null;
  fee: { note: string; amount: number | null };
  warnings: string[];
  sources: { label: string; url: string; note?: string | null }[];
  sourcedOn: string | null;
  verifiedDate: string | null;
  verifiedSource: string | null;
  outstanding?: string[];
  photos?: Photo[];
  /* Town parks correct and get reported on exactly like state parks do — the
     promise on /how-we-verify/ isn't scoped to one dataset. */
  corrections?: Correction[];
  reports?: FieldReport[];
  fieldNotes?: FieldNote[];
  verdict?: Verdict;
}

/* ------------------------------------------------------------- rendering -- */

export type Answer = { text: string; state: "yes" | "no" | "unknown" };

export function tri(v: boolean | null, yes = "Yes", no = "No"): Answer {
  if (v === null || v === undefined) return { text: "Not confirmed", state: "unknown" };
  return v ? { text: yes, state: "yes" } : { text: no, state: "no" };
}

/**
 * The restroom answer in the words someone needs — not "true". A permanent
 * block, a portable unit and a block that opens after Memorial Day are three
 * different answers, and the third ruins an April trip.
 */
export function restroomAnswer(r: Restrooms): Answer {
  if (r.present === null || r.present === undefined) {
    return { text: "Not confirmed", state: "unknown" };
  }
  if (!r.present) return { text: "None", state: "no" };
  const bits = [r.type === "portable" ? "Portable units" : "Yes"];
  if (r.caveat) bits.push(r.caveat);
  if (r.seasonal === true) bits.push("seasonal only");
  if (r.seasonal === null && !r.caveat) bits.push("season not confirmed");
  return { text: bits.join(" — "), state: "yes" };
}

export const STATE_FEATURE_LABELS: [keyof StateParkFeatures, string][] = [
  ["waterfall", "Waterfall"],
  ["beach", "Beach"],
  ["swimming", "Swimming"],
  ["restrooms", "Restrooms"],
  ["picnic", "Picnic areas"],
  ["showers", "Showers"],
  ["camping", "Camping"],
  ["cabins", "Cabins"],
  ["trails", "Trails"],
  ["boatLaunch", "Boat launch"],
  ["boatRentals", "Boat rentals"],
  ["fishing", "Fishing"],
  ["winterUse", "Winter use"],
  ["petsAllowed", "Pets"],
];

export const REGIONAL_FACILITY_LABELS: [keyof RegionalFacilities, string][] = [
  ["playground", "Playground"],
  ["swimming", "Swimming"],
  ["beach", "Beach"],
  ["picnic", "Picnic tables"],
  ["pavilion", "Pavilion"],
  ["grills", "Grills"],
  ["trails", "Trails"],
  ["sports", "Courts / fields"],
  ["boatLaunch", "Boat launch"],
  ["fishing", "Fishing"],
  ["pavedPath", "Paved path"],
  ["winterUse", "Winter use"],
];

/**
 * The three that decide whether an outing works, and the reason this site
 * leads with restrooms everywhere. Marked in the data rather than at each
 * render site, so a chip can't be emphasised on one page and not another.
 */
const EMPHASIS = new Set(["restrooms", "water", "showers"]);

export interface Tag {
  key: string;
  label: string;
  emphasis: boolean;
}

const tag = ([key, label]: [string, string]): Tag => ({
  key,
  label,
  emphasis: EMPHASIS.has(key),
});

export const presentState = (p: StatePark): Tag[] =>
  STATE_FEATURE_LABELS.filter(([k]) => p.features[k] === true).map((e) => tag(e as [string, string]));

export const presentRegional = (p: RegionalPark): Tag[] =>
  REGIONAL_FACILITY_LABELS.filter(([k]) => p.facilities[k] === true).map((e) => tag(e as [string, string]));

export function completenessState(p: StatePark) {
  const v = STATE_FEATURE_LABELS.map(([k]) => p.features[k]);
  return { known: v.filter((x) => x !== null && x !== undefined).length, total: v.length };
}

/** Restrooms count as a field here — it's the one people ask about. */
export function completenessRegional(p: RegionalPark) {
  const v: (boolean | null)[] = [
    p.restrooms.present,
    ...REGIONAL_FACILITY_LABELS.map(([k]) => p.facilities[k]),
  ];
  return { known: v.filter((x) => x !== null && x !== undefined).length, total: v.length };
}

/** Reservation status, as a flag with a redundant texture channel. */
/**
 * The reservation rule as one sentence, built from the data.
 *
 * A helper rather than page markup because the index card and the park page
 * both need to say this and must not be able to drift apart. The weekday
 * clause is the whole point: it is the half of the rule that stops someone
 * cancelling a Tuesday.
 */
export function reservationLine(r: Reservation): string | null {
  if (r.required !== true) return null;
  const bits: string[] = [];
  bits.push(
    r.scope === "weekends"
      ? "Weekends and holidays need a day-use reservation. Weekdays you can turn up and pay at the gate"
      : "A day-use reservation is needed",
  );
  if (r.window) bits.push(r.window);
  if (r.bookAhead) bits.push(r.bookAhead.replace(/^Opens /, "Booking opens "));
  return bits.join(". ").replace(/\.\.$/, ".") + ".";
}

export function reservationFlag(r: Reservation): {
  word: string;
  bar: "bar-solid" | "bar-dotted" | "bar-hatch";
  chip: string;
  icon: "check" | "alert" | "cross";
} {
  if (r.required === true)
    return {
      word: r.scope === "weekends" ? "Reservation at weekends" : "Reservation required",
      bar: "bar-hatch",
      chip: "bg-flag-red-bearing text-white",
      icon: "alert",
    };
  if (r.required === false)
    return {
      word: "No reservation needed",
      bar: "bar-solid",
      chip: "bg-flag-green-bearing text-white",
      icon: "check",
    };
  return {
    word: "Not confirmed",
    bar: "bar-dotted",
    chip: "bg-flag-amber text-ink",
    icon: "alert",
  };
}

/* ----------------------------------------------------------------- asks -- */

/**
 * Reader-facing questions for the report form.
 *
 * DERIVED FROM THE DATA, never from `outstanding`. Those entries are written
 * for whoever is making the phone calls — "PRIORITY: get the admission price,
 * and whether there is a separate parking charge" — and putting that in front
 * of a visitor asks them to care about our workflow. They don't. They want the
 * answer too.
 *
 * So the questions come from which fields are actually null, phrased the way
 * someone standing in the parking lot would say them. That also means they can
 * never drift out of date: fill the field in and the question stops appearing.
 */
const STATE_ASKS: [keyof StateParkFeatures, string][] = [
  ["restrooms", "Are there restrooms?"],
  ["petsAllowed", "Are dogs allowed?"],
  ["picnic", "Are there picnic tables?"],
  ["showers", "Are there showers?"],
  ["beach", "Is there a beach?"],
  ["swimming", "Can you swim?"],
  ["camping", "Can you camp?"],
  ["cabins", "Are there cabins?"],
  ["boatRentals", "Can you rent a boat?"],
  ["boatLaunch", "Is there a boat launch?"],
  ["winterUse", "Is it open in winter?"],
  ["trails", "Are there trails?"],
  ["fishing", "Can you fish?"],
];

const REGIONAL_ASKS: [keyof RegionalFacilities, string][] = [
  ["playground", "Is there a playground?"],
  ["swimming", "Can you swim?"],
  ["beach", "Is there a beach?"],
  ["picnic", "Are there picnic tables?"],
  ["pavilion", "Is there a pavilion?"],
  ["sports", "Are there courts or fields?"],
  ["pavedPath", "Is there a paved path?"],
  ["trails", "Are there trails?"],
  ["boatLaunch", "Is there a boat launch?"],
  ["winterUse", "Is it used in winter?"],
];

/** Four at most. A wall of questions reads as a survey and gets nothing back. */
export function asksForState(p: StatePark): string[] {
  const out: string[] = [];
  if (!p.hours) out.push("What are the hours?");
  for (const [k, q] of STATE_ASKS) {
    if (p.features[k] === null || p.features[k] === undefined) out.push(q);
  }
  if (p.services && p.services.giftShop === null && p.services.campStore === null) {
    out.push("Is there a shop?");
  }
  return out.slice(0, 4);
}

export function asksForRegional(p: RegionalPark): string[] {
  const out: string[] = [];
  if (p.restrooms.present === null || p.restrooms.present === undefined) {
    out.push("Are there restrooms?");
  }
  if (!p.hours) out.push("What are the hours?");
  for (const [k, q] of REGIONAL_ASKS) {
    if (p.facilities[k] === null || p.facilities[k] === undefined) out.push(q);
  }
  return out.slice(0, 4);
}

/* ------------------------------------------------------------- goodFor -- */

/**
 * Situation tags.
 *
 * The filters on this site were attributes: restrooms, pavilion, paved path.
 * People don't search in attributes. They search in situations. "Somewhere to
 * take a toddler for an hour" is the actual query; "playground: true" is our
 * internal shape for it.
 *
 * DERIVED, never authored. Every tag is a rule over fields that already exist,
 * so a tag appears the moment the data supports it and vanishes when it
 * doesn't. Nobody has to remember to retag anything, and a tag can never claim
 * something the facts table contradicts.
 *
 * A tag is only awarded on a CONFIRMED true. Unknown never earns one, because
 * the whole point of a situation tag is that you can trust it enough to drive
 * there.
 */
export interface GoodForTag {
  slug: string;
  label: string;
}

const TAGS: { slug: string; label: string; state?: (p: StatePark) => boolean; regional?: (p: RegionalPark) => boolean }[] = [
  {
    slug: "restrooms-that-exist",
    label: "Restrooms that exist",
    state: (p) => p.features.restrooms === true,
    regional: (p) => p.restrooms.present === true && !p.restrooms.caveat,
  },
  {
    slug: "no-booking-needed",
    label: "No booking needed",
    state: (p) => p.reservation.required === false,
    regional: () => true,
  },
  {
    slug: "free",
    label: "Free",
    state: (p) => p.fee.amount === 0,
    regional: (p) => p.fee.amount === 0,
  },
  {
    slug: "burn-off-an-hour",
    label: "Burn off an hour",
    state: (p) => p.features.trails === true,
    regional: (p) => p.facilities.playground === true || p.facilities.sports === true,
  },
  {
    slug: "somewhere-to-sit",
    label: "Somewhere to sit",
    state: (p) => p.features.picnic === true,
    regional: (p) => p.facilities.picnic === true || p.facilities.pavilion === true,
  },
  {
    slug: "get-in-the-water",
    label: "Get in the water",
    state: (p) => p.features.swimming === true || p.features.beach === true,
    regional: (p) => p.facilities.swimming === true || p.facilities.beach === true,
  },
  {
    slug: "bring-the-dog",
    label: "Bring the dog",
    state: (p) => p.features.petsAllowed === true,
  },
  {
    slug: "stay-the-night",
    label: "Stay the night",
    state: (p) => p.features.camping === true || p.features.cabins === true,
  },
  {
    slug: "worth-it-in-winter",
    label: "Worth it in winter",
    state: (p) => p.features.winterUse === true,
    regional: (p) => p.facilities.winterUse === true,
  },
  {
    slug: "pushchair-friendly",
    label: "Stroller-friendly",
    regional: (p) => p.facilities.pavedPath === true,
  },
];

export const goodForState = (p: StatePark): GoodForTag[] =>
  TAGS.filter((t) => t.state?.(p)).map(({ slug, label }) => ({ slug, label }));

export const goodForRegional = (p: RegionalPark): GoodForTag[] =>
  TAGS.filter((t) => t.regional?.(p)).map(({ slug, label }) => ({ slug, label }));

/** Every tag that at least one record earns, for building the filter pages. */
export function allGoodFor(state: StatePark[], regional: RegionalPark[]) {
  return TAGS.map(({ slug, label }) => ({
    slug,
    label,
    parks: [
      ...state.filter((p) => goodForState(p).some((t) => t.slug === slug)).map((p) => ({
        name: p.name, href: `/parks/${p.slug}/`, kind: p.kind, town: p.town, verdict: p.verdict ?? null, photo: p.photos?.[0] ?? null, warnings: p.warnings ?? [],
      })),
      ...regional.filter((p) => goodForRegional(p).some((t) => t.slug === slug)).map((p) => ({
        name: p.name, href: `/parks/regional/${p.slug}/`, kind: "Town park", town: p.town, verdict: p.verdict ?? null, photo: p.photos?.[0] ?? null, warnings: p.warnings ?? [],
      })),
    ],
  })).filter((t) => t.parks.length > 0);
}
