/**
 * Generate CALL-SHEET.md — every outstanding verification, in one place.
 *
 * Generic: discovers every JSON file in src/data/ and pulls `outstanding[]`
 * from any record shape it finds, at any nesting depth. Add a data file and it
 * appears here with no code change.
 *
 * Generated, never hand-edited. A hand-kept list drifts within a week and then
 * lies about what's been done. An item disappears when its record gets both
 * `verifiedDate` and `verifiedSource`.
 *
 * A record only appears here if it has an `outstanding[]` array, so put the
 * actual questions there when you create the record — not "confirm details",
 * but the questions in the order you'd ask them on the call. That array is the
 * deliverable; this script just collates it.
 *
 * Ordering is by CONSEQUENCE, not by file. Set PRIORITY below for the region:
 * anything safety-critical first, then the wedge, then the rest. In the
 * reference build emergency vet numbers led, because they were the only data
 * where being wrong hurt an animal rather than costing a trip.
 *
 * Run: npm run calls
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const DATA_DIR = "src/data";

/**
 * Files listed here come first, in this order. Anything else follows
 * alphabetically. Use it to put the consequential calls at the top.
 */
const PRIORITY = [
  // "emergency.json",
  // "towns.json",
];

/** A record counts as done when it has been confirmed first-hand. */
const done = (r) => Boolean(r?.verifiedDate && r?.verifiedSource);

/** Best-effort human label for a record. */
const nameOf = (r, fallback) =>
  r?.name ?? r?.title ?? r?.label ?? r?.headline ?? r?.slug ?? fallback;

/** Best-effort phone for a record. */
const phoneOf = (r) => r?.phone ?? r?.callTo?.phone ?? null;

/**
 * Walk anything — array, object, nested block — and yield every node that has
 * an `outstanding` array. Data shapes differ per section and this avoids
 * teaching the script about each one.
 */
function* withOutstanding(node, path = []) {
  if (Array.isArray(node)) {
    for (const [i, v] of node.entries()) yield* withOutstanding(v, [...path, String(i)]);
    return;
  }
  if (!node || typeof node !== "object") return;

  if (Array.isArray(node.outstanding) && node.outstanding.length && !done(node)) {
    yield { record: node, path };
  }
  for (const [k, v] of Object.entries(node)) {
    if (k === "outstanding" || k === "sources") continue;
    if (v && typeof v === "object") yield* withOutstanding(v, [...path, k]);
  }
}

if (!existsSync(DATA_DIR)) {
  console.error(`  ✗ No ${DATA_DIR}/ — nothing to generate yet.`);
  process.exit(0);
}

const files = readdirSync(DATA_DIR).filter((f) => f.endsWith(".json"));
files.sort((a, b) => {
  const ia = PRIORITY.indexOf(a), ib = PRIORITY.indexOf(b);
  if (ia !== -1 || ib !== -1) return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
  return a.localeCompare(b);
});

const lines = [];
let open = 0;

lines.push(
  `# Call sheet`,
  ``,
  `> Generated by \`npm run calls\` from the data files. Do not edit by hand —`,
  `> tick items off by filling in \`verifiedDate\` and \`verifiedSource\` on the`,
  `> record itself, then re-run. An item disappears when its record is confirmed.`,
  ``,
  `Ordered by consequence. Whatever is most costly to get wrong comes first.`,
  ``,
);

for (const file of files) {
  let data;
  try {
    data = JSON.parse(readFileSync(join(DATA_DIR, file), "utf8"));
  } catch (e) {
    lines.push(`> ⚠ Could not parse \`${file}\`: ${e.message}`, ``);
    continue;
  }

  const found = [...withOutstanding(data)];
  if (!found.length) continue;

  const section = file.replace(/\.json$/, "").replace(/[-_]/g, " ");
  lines.push(``, `## ${section.charAt(0).toUpperCase()}${section.slice(1)}`, ``);

  for (const { record, path } of found) {
    const name = nameOf(record, path.join(" › ") || file);
    const phone = phoneOf(record);
    open += record.outstanding.length;
    lines.push(`### ${name}${phone ? ` — ${phone}` : ""}`, ``);
    for (const item of record.outstanding) lines.push(`- [ ] ${item}`);
    lines.push(``);
  }
}

lines.push(
  ``,
  `---`,
  ``,
  `**${open} open items.** Every one is a fact this site cannot confirm until`,
  `someone picks up a phone. That is the moat, not overhead.`,
  ``,
);

writeFileSync("CALL-SHEET.md", lines.join("\n"));
console.log(`  ✓ CALL-SHEET.md — ${open} open items across ${files.length} data files`);
